// Grade-appropriate vocabulary lists. Mix of Dolch/Fry sight words and
// vocabulary words with definitions, plus a small synonym table.
//
// Each entry has at least `word`; richer entries include `def` (definition)
// and optional `sentence` (cloze template with `___` where the word goes).

export const WORDS = {
  '1st Grade': [
    { word: 'cat', def: 'a small pet that purrs', sentence: 'The ___ chased the mouse.' },
    { word: 'dog', def: 'a furry pet that barks', sentence: 'My ___ wags its tail.' },
    { word: 'run', def: 'to move very fast on your feet', sentence: 'I like to ___ at recess.' },
    { word: 'jump', def: 'to push off the ground with your legs', sentence: 'Frogs love to ___.' },
    { word: 'big', def: 'large in size', sentence: 'The elephant is very ___.' },
    { word: 'red', def: 'the color of fire trucks', sentence: 'Apples are often ___.' },
    { word: 'sun', def: 'the bright star in the daytime sky', sentence: 'The ___ shines all day.' },
    { word: 'moon', def: 'the round light in the night sky', sentence: 'The ___ comes out at night.' },
    { word: 'cup', def: 'something you drink out of', sentence: 'I poured milk into the ___.' },
    { word: 'bed', def: 'what you sleep on', sentence: 'I sleep in my ___.' },
    { word: 'top', def: 'the highest part of something', sentence: 'Snow is on the ___ of the hill.' },
    { word: 'fish', def: 'an animal that lives in water', sentence: 'A ___ swims in the lake.' },
    { word: 'bird', def: 'an animal with feathers that flies', sentence: 'A ___ sings in the tree.' },
    { word: 'car', def: 'a thing you drive on the road', sentence: 'The ___ drove fast.' },
    { word: 'book', def: 'a thing you read', sentence: 'I read a ___ before bed.' },
    { word: 'milk', def: 'a white drink from cows', sentence: 'Cows give us ___.' },
    { word: 'tree', def: 'a big plant with leaves and branches', sentence: 'Birds nest in the ___.' },
    { word: 'rain', def: 'water falling from clouds', sentence: 'I bring an umbrella when it ___s.' },
    { word: 'play', def: 'to have fun with games or toys', sentence: 'Kids love to ___.' },
    { word: 'fast', def: 'moving with high speed', sentence: 'A cheetah is very ___.' }
  ],
  '2nd Grade': [
    { word: 'happy', def: 'feeling good and joyful', sentence: 'I felt ___ on my birthday.' },
    { word: 'angry', def: 'feeling mad or upset', sentence: 'He was ___ when his bike broke.' },
    { word: 'small', def: 'not big', sentence: 'The mouse was very ___.' },
    { word: 'large', def: 'very big', sentence: 'The whale is ___.' },
    { word: 'quick', def: 'moving fast', sentence: 'The rabbit is ___.' },
    { word: 'slow', def: 'not fast', sentence: 'A turtle walks very ___.' },
    { word: 'bright', def: 'giving a lot of light', sentence: 'The sun is very ___.' },
    { word: 'dark', def: 'with very little light', sentence: 'The cave was ___.' },
    { word: 'friend', def: 'someone you like and play with', sentence: 'My best ___ lives next door.' },
    { word: 'family', def: 'people you are related to', sentence: 'My ___ ate dinner together.' },
    { word: 'because', def: 'for the reason that', sentence: 'I went home ___ I was tired.' },
    { word: 'people', def: 'humans', sentence: 'Many ___ went to the park.' },
    { word: 'water', def: 'clear liquid we drink', sentence: 'Plants need ___ to grow.' },
    { word: 'house', def: 'a building where people live', sentence: 'We painted our ___ blue.' },
    { word: 'school', def: 'a place where you learn', sentence: 'I ride the bus to ___.' },
    { word: 'morning', def: 'the early part of the day', sentence: 'I eat breakfast every ___.' },
    { word: 'night', def: 'the time when it is dark', sentence: 'Stars come out at ___.' },
    { word: 'animal', def: 'a living thing that is not a plant', sentence: 'A lion is a wild ___.' },
    { word: 'flower', def: 'the colorful part of a plant', sentence: 'A bee landed on the ___.' },
    { word: 'garden', def: 'a place where plants grow', sentence: 'Tomatoes grow in our ___.' }
  ],
  '3rd Grade': [
    { word: 'gigantic', def: 'extremely large', sentence: 'The ___ ship sailed into the harbor.' },
    { word: 'tiny', def: 'very small', sentence: 'A ___ ant crawled across the page.' },
    { word: 'enormous', def: 'unusually large', sentence: 'The ___ elephant ate hay.' },
    { word: 'whisper', def: 'to speak very softly', sentence: 'I had to ___ in the library.' },
    { word: 'shout', def: 'to say something very loudly', sentence: 'I had to ___ to be heard.' },
    { word: 'beautiful', def: 'very pretty to look at', sentence: 'The sunset was ___.' },
    { word: 'ugly', def: 'not pleasant to look at', sentence: 'The troll was ___.' },
    { word: 'different', def: 'not the same', sentence: 'These two pictures are ___.' },
    { word: 'important', def: 'mattering a lot', sentence: 'Eating breakfast is ___.' },
    { word: 'curious', def: 'wanting to know about something', sentence: 'The ___ cat sniffed the box.' },
    { word: 'brave', def: 'not afraid', sentence: 'The ___ knight fought the dragon.' },
    { word: 'silly', def: 'goofy or funny', sentence: 'The ___ clown made us laugh.' },
    { word: 'enough', def: 'as much as is needed', sentence: 'Do we have ___ food?' },
    { word: 'travel', def: 'to go from one place to another', sentence: 'We ___ to Grandma\'s in summer.' },
    { word: 'forest', def: 'a large area with many trees', sentence: 'Owls live in the ___.' },
    { word: 'mountain', def: 'a very tall hill', sentence: 'Snow covered the ___ top.' },
    { word: 'machine', def: 'a thing built to do work', sentence: 'A washing ___ cleans clothes.' },
    { word: 'planet', def: 'a large body that orbits a star', sentence: 'Earth is a ___.' },
    { word: 'invent', def: 'to make something new for the first time', sentence: 'Edison helped ___ the light bulb.' },
    { word: 'observe', def: 'to watch carefully', sentence: 'Scientists ___ how plants grow.' }
  ],
  '4th Grade': [
    { word: 'ancient', def: 'extremely old', sentence: 'The ___ city was buried for centuries.' },
    { word: 'modern', def: 'happening now or recently', sentence: 'Cell phones are a ___ invention.' },
    { word: 'necessary', def: 'needed; required', sentence: 'Water is ___ for life.' },
    { word: 'separate', def: 'apart from one another', sentence: 'Please ___ the apples from the oranges.' },
    { word: 'immediately', def: 'right away', sentence: 'Please answer the door ___.' },
    { word: 'fascinating', def: 'very interesting', sentence: 'Space is ___.' },
    { word: 'discover', def: 'to find for the first time', sentence: 'Pioneers wanted to ___ new lands.' },
    { word: 'investigate', def: 'to look into carefully', sentence: 'The detective will ___ the case.' },
    { word: 'frequent', def: 'happening often', sentence: 'It is a ___ visitor here.' },
    { word: 'occasional', def: 'happening sometimes', sentence: 'Only ___ snow falls in spring.' },
    { word: 'generous', def: 'willing to give freely', sentence: 'Our ___ neighbor brought cookies.' },
    { word: 'selfish', def: 'thinking only about yourself', sentence: 'It is ___ to never share.' },
    { word: 'tremble', def: 'to shake slightly', sentence: 'The leaves ___ in the wind.' },
    { word: 'enormous', def: 'unusually large', sentence: 'The ___ ship sailed into the harbor.' },
    { word: 'fragile', def: 'easily broken', sentence: 'Be careful — that vase is ___.' },
    { word: 'distance', def: 'the space between two things', sentence: 'The ___ to school is one mile.' },
    { word: 'reveal', def: 'to show something hidden', sentence: 'The magician will ___ the secret.' },
    { word: 'predict', def: 'to guess what will happen', sentence: 'Scientists ___ the weather.' },
    { word: 'opinion', def: 'what you think or believe', sentence: 'Everyone has an ___ about pizza toppings.' },
    { word: 'evidence', def: 'facts that prove something', sentence: 'The ___ pointed to the suspect.' }
  ],
  '5th Grade': [
    { word: 'independence', def: 'freedom from control by others', sentence: 'Many countries fought for ___.' },
    { word: 'conscience', def: 'sense of right and wrong', sentence: 'Her ___ told her to apologize.' },
    { word: 'achievement', def: 'something done with effort', sentence: 'Graduating was a great ___.' },
    { word: 'persuade', def: 'to convince someone', sentence: 'Can you ___ him to come along?' },
    { word: 'sufficient', def: 'enough for the purpose', sentence: 'Two slices is ___ for me.' },
    { word: 'analyze', def: 'to examine carefully', sentence: 'Detectives ___ clues.' },
    { word: 'hypothesis', def: 'an educated guess to test', sentence: 'Her ___ was that plants grow taller in sunlight.' },
    { word: 'environment', def: 'the surroundings where you live', sentence: 'Pollution harms the ___.' },
    { word: 'ecosystem', def: 'a community of living things and their habitat', sentence: 'A coral reef is an ___.' },
    { word: 'democracy', def: 'a government chosen by the people', sentence: 'In a ___, citizens vote.' },
    { word: 'civilization', def: 'an advanced human society', sentence: 'Ancient Egypt was a great ___.' },
    { word: 'mysterious', def: 'hard to understand or explain', sentence: 'A ___ light glowed in the woods.' },
    { word: 'curious', def: 'wanting to know about something', sentence: 'A ___ student asks lots of questions.' },
    { word: 'sympathy', def: 'caring about another\'s feelings', sentence: 'She showed ___ when the puppy hurt its paw.' },
    { word: 'tradition', def: 'a long-followed custom', sentence: 'Eating turkey is a Thanksgiving ___.' },
    { word: 'reluctant', def: 'unwilling; hesitant', sentence: 'He was ___ to try the spinach.' },
    { word: 'optimistic', def: 'expecting good things', sentence: 'She felt ___ about the test.' },
    { word: 'pessimistic', def: 'expecting bad things', sentence: 'He was ___ about the rainy forecast.' },
    { word: 'consequence', def: 'a result of an action', sentence: 'Every choice has a ___.' },
    { word: 'fortunate', def: 'lucky', sentence: 'We were ___ to find a parking spot.' }
  ]
}

// Synonym pairs for the synonym question template
export const SYNONYMS = [
  ['happy', 'glad'],
  ['big', 'large'],
  ['small', 'tiny'],
  ['quick', 'fast'],
  ['begin', 'start'],
  ['end', 'finish'],
  ['hard', 'difficult'],
  ['easy', 'simple'],
  ['smart', 'clever'],
  ['quiet', 'silent'],
  ['scared', 'afraid'],
  ['brave', 'courageous'],
  ['gigantic', 'huge'],
  ['ancient', 'old'],
  ['modern', 'new'],
  ['shout', 'yell']
]

// Antonym pairs
export const ANTONYMS = [
  ['hot', 'cold'],
  ['big', 'small'],
  ['happy', 'sad'],
  ['quick', 'slow'],
  ['bright', 'dark'],
  ['hard', 'soft'],
  ['high', 'low'],
  ['up', 'down'],
  ['in', 'out'],
  ['begin', 'end'],
  ['ancient', 'modern'],
  ['generous', 'selfish'],
  ['optimistic', 'pessimistic'],
  ['frequent', 'rare']
]
