// Grade-appropriate vocabulary lists. Mix of Dolch/Fry sight words and
// vocabulary words with definitions, plus a small synonym table.
//
// Each entry: `word`, optional `def` (definition), optional `sentence`
// (cloze template with `___` where the word goes), and optional `emoji`
// (a single-glyph visual hint shown alongside the question).

export const WORDS = {
  '1st Grade': [
    { word: 'cat', def: 'a small pet that purrs', sentence: 'The ___ chased the mouse.', emoji: '🐱' },
    { word: 'dog', def: 'a furry pet that barks', sentence: 'My ___ wags its tail.', emoji: '🐶' },
    { word: 'run', def: 'to move very fast on your feet', sentence: 'I like to ___ at recess.', emoji: '🏃' },
    { word: 'jump', def: 'to push off the ground with your legs', sentence: 'Frogs love to ___.', emoji: '🦘' },
    { word: 'big', def: 'large in size', sentence: 'The elephant is very ___.', emoji: '🐘' },
    { word: 'red', def: 'the color of fire trucks', sentence: 'Apples are often ___.', emoji: '🔴' },
    { word: 'sun', def: 'the bright star in the daytime sky', sentence: 'The ___ shines all day.', emoji: '☀️' },
    { word: 'moon', def: 'the round light in the night sky', sentence: 'The ___ comes out at night.', emoji: '🌙' },
    { word: 'cup', def: 'something you drink out of', sentence: 'I poured milk into the ___.', emoji: '🥤' },
    { word: 'bed', def: 'what you sleep on', sentence: 'I sleep in my ___.', emoji: '🛏️' },
    { word: 'top', def: 'the highest part of something', sentence: 'Snow is on the ___ of the hill.', emoji: '⛰️' },
    { word: 'fish', def: 'an animal that lives in water', sentence: 'A ___ swims in the lake.', emoji: '🐟' },
    { word: 'bird', def: 'an animal with feathers that flies', sentence: 'A ___ sings in the tree.', emoji: '🐦' },
    { word: 'car', def: 'a thing you drive on the road', sentence: 'The ___ drove fast.', emoji: '🚗' },
    { word: 'book', def: 'a thing you read', sentence: 'I read a ___ before bed.', emoji: '📖' },
    { word: 'milk', def: 'a white drink from cows', sentence: 'Cows give us ___.', emoji: '🥛' },
    { word: 'tree', def: 'a big plant with leaves and branches', sentence: 'Birds nest in the ___.', emoji: '🌳' },
    { word: 'rain', def: 'water falling from clouds', sentence: 'I bring an umbrella when it ___s.', emoji: '🌧️' },
    { word: 'play', def: 'to have fun with games or toys', sentence: 'Kids love to ___.', emoji: '🎮' },
    { word: 'fast', def: 'moving with high speed', sentence: 'A cheetah is very ___.', emoji: '⚡' }
  ],
  '2nd Grade': [
    { word: 'happy', def: 'feeling good and joyful', sentence: 'I felt ___ on my birthday.', emoji: '😊' },
    { word: 'angry', def: 'feeling mad or upset', sentence: 'He was ___ when his bike broke.', emoji: '😠' },
    { word: 'small', def: 'not big', sentence: 'The mouse was very ___.', emoji: '🐭' },
    { word: 'large', def: 'very big', sentence: 'The whale is ___.', emoji: '🐋' },
    { word: 'quick', def: 'moving fast', sentence: 'The rabbit is ___.', emoji: '🐇' },
    { word: 'slow', def: 'not fast', sentence: 'A turtle walks very ___.', emoji: '🐢' },
    { word: 'bright', def: 'giving a lot of light', sentence: 'The sun is very ___.', emoji: '💡' },
    { word: 'dark', def: 'with very little light', sentence: 'The cave was ___.', emoji: '🌑' },
    { word: 'friend', def: 'someone you like and play with', sentence: 'My best ___ lives next door.', emoji: '🤝' },
    { word: 'family', def: 'people you are related to', sentence: 'My ___ ate dinner together.', emoji: '👨‍👩‍👧‍👦' },
    { word: 'because', def: 'for the reason that', sentence: 'I went home ___ I was tired.', emoji: '💭' },
    { word: 'people', def: 'humans', sentence: 'Many ___ went to the park.', emoji: '👥' },
    { word: 'water', def: 'clear liquid we drink', sentence: 'Plants need ___ to grow.', emoji: '💧' },
    { word: 'house', def: 'a building where people live', sentence: 'We painted our ___ blue.', emoji: '🏠' },
    { word: 'school', def: 'a place where you learn', sentence: 'I ride the bus to ___.', emoji: '🏫' },
    { word: 'morning', def: 'the early part of the day', sentence: 'I eat breakfast every ___.', emoji: '🌅' },
    { word: 'night', def: 'the time when it is dark', sentence: 'Stars come out at ___.', emoji: '🌃' },
    { word: 'animal', def: 'a living thing that is not a plant', sentence: 'A lion is a wild ___.', emoji: '🦁' },
    { word: 'flower', def: 'the colorful part of a plant', sentence: 'A bee landed on the ___.', emoji: '🌸' },
    { word: 'garden', def: 'a place where plants grow', sentence: 'Tomatoes grow in our ___.', emoji: '🌱' }
  ],
  '3rd Grade': [
    { word: 'gigantic', def: 'extremely large', sentence: 'The ___ ship sailed into the harbor.', emoji: '🦣' },
    { word: 'tiny', def: 'very small', sentence: 'A ___ ant crawled across the page.', emoji: '🐜' },
    { word: 'enormous', def: 'unusually large', sentence: 'The ___ elephant ate hay.', emoji: '🐘' },
    { word: 'whisper', def: 'to speak very softly', sentence: 'I had to ___ in the library.', emoji: '🤫' },
    { word: 'shout', def: 'to say something very loudly', sentence: 'I had to ___ to be heard.', emoji: '📣' },
    { word: 'beautiful', def: 'very pretty to look at', sentence: 'The sunset was ___.', emoji: '🌸' },
    { word: 'ugly', def: 'not pleasant to look at', sentence: 'The troll was ___.', emoji: '👹' },
    { word: 'different', def: 'not the same', sentence: 'These two pictures are ___.', emoji: '🔀' },
    { word: 'important', def: 'mattering a lot', sentence: 'Eating breakfast is ___.', emoji: '⭐' },
    { word: 'curious', def: 'wanting to know about something', sentence: 'The ___ cat sniffed the box.', emoji: '🔍' },
    { word: 'brave', def: 'not afraid', sentence: 'The ___ knight fought the dragon.', emoji: '🦁' },
    { word: 'silly', def: 'goofy or funny', sentence: 'The ___ clown made us laugh.', emoji: '🤪' },
    { word: 'enough', def: 'as much as is needed', sentence: 'Do we have ___ food?', emoji: '✅' },
    { word: 'travel', def: 'to go from one place to another', sentence: 'We ___ to Grandma\'s in summer.', emoji: '✈️' },
    { word: 'forest', def: 'a large area with many trees', sentence: 'Owls live in the ___.', emoji: '🌲' },
    { word: 'mountain', def: 'a very tall hill', sentence: 'Snow covered the ___ top.', emoji: '⛰️' },
    { word: 'machine', def: 'a thing built to do work', sentence: 'A washing ___ cleans clothes.', emoji: '⚙️' },
    { word: 'planet', def: 'a large body that orbits a star', sentence: 'Earth is a ___.', emoji: '🪐' },
    { word: 'invent', def: 'to make something new for the first time', sentence: 'Edison helped ___ the light bulb.', emoji: '💡' },
    { word: 'observe', def: 'to watch carefully', sentence: 'Scientists ___ how plants grow.', emoji: '🔭' }
  ],
  '4th Grade': [
    { word: 'ancient', def: 'extremely old', sentence: 'The ___ city was buried for centuries.', emoji: '🏛️' },
    { word: 'modern', def: 'happening now or recently', sentence: 'Cell phones are a ___ invention.', emoji: '📱' },
    { word: 'necessary', def: 'needed; required', sentence: 'Water is ___ for life.', emoji: '🚰' },
    { word: 'separate', def: 'apart from one another', sentence: 'Please ___ the apples from the oranges.', emoji: '↔️' },
    { word: 'immediately', def: 'right away', sentence: 'Please answer the door ___.', emoji: '⏱️' },
    { word: 'fascinating', def: 'very interesting', sentence: 'Space is ___.', emoji: '✨' },
    { word: 'discover', def: 'to find for the first time', sentence: 'Pioneers wanted to ___ new lands.', emoji: '🧭' },
    { word: 'investigate', def: 'to look into carefully', sentence: 'The detective will ___ the case.', emoji: '🕵️' },
    { word: 'frequent', def: 'happening often', sentence: 'It is a ___ visitor here.', emoji: '🔁' },
    { word: 'occasional', def: 'happening sometimes', sentence: 'Only ___ snow falls in spring.', emoji: '❄️' },
    { word: 'generous', def: 'willing to give freely', sentence: 'Our ___ neighbor brought cookies.', emoji: '🎁' },
    { word: 'selfish', def: 'thinking only about yourself', sentence: 'It is ___ to never share.', emoji: '🪞' },
    { word: 'tremble', def: 'to shake slightly', sentence: 'The leaves ___ in the wind.', emoji: '🍃' },
    { word: 'fragile', def: 'easily broken', sentence: 'Be careful — that vase is ___.', emoji: '🥚' },
    { word: 'distance', def: 'the space between two things', sentence: 'The ___ to school is one mile.', emoji: '📏' },
    { word: 'reveal', def: 'to show something hidden', sentence: 'The magician will ___ the secret.', emoji: '🎩' },
    { word: 'predict', def: 'to guess what will happen', sentence: 'Scientists ___ the weather.', emoji: '🔮' },
    { word: 'opinion', def: 'what you think or believe', sentence: 'Everyone has an ___ about pizza toppings.', emoji: '💭' },
    { word: 'evidence', def: 'facts that prove something', sentence: 'The ___ pointed to the suspect.', emoji: '🔬' },
    { word: 'communicate', def: 'to share information with others', sentence: 'We ___ with words and gestures.', emoji: '💬' }
  ],
  '5th Grade': [
    { word: 'independence', def: 'freedom from control by others', sentence: 'Many countries fought for ___.', emoji: '🗽' },
    { word: 'conscience', def: 'sense of right and wrong', sentence: 'Her ___ told her to apologize.', emoji: '😇' },
    { word: 'achievement', def: 'something done with effort', sentence: 'Graduating was a great ___.', emoji: '🏆' },
    { word: 'persuade', def: 'to convince someone', sentence: 'Can you ___ him to come along?', emoji: '🗣️' },
    { word: 'sufficient', def: 'enough for the purpose', sentence: 'Two slices is ___ for me.', emoji: '✅' },
    { word: 'analyze', def: 'to examine carefully', sentence: 'Detectives ___ clues.', emoji: '🔍' },
    { word: 'hypothesis', def: 'an educated guess to test', sentence: 'Her ___ was that plants grow taller in sunlight.', emoji: '🧪' },
    { word: 'environment', def: 'the surroundings where you live', sentence: 'Pollution harms the ___.', emoji: '🌍' },
    { word: 'ecosystem', def: 'a community of living things and their habitat', sentence: 'A coral reef is an ___.', emoji: '🐠' },
    { word: 'democracy', def: 'a government chosen by the people', sentence: 'In a ___, citizens vote.', emoji: '🗳️' },
    { word: 'civilization', def: 'an advanced human society', sentence: 'Ancient Egypt was a great ___.', emoji: '🏛️' },
    { word: 'mysterious', def: 'hard to understand or explain', sentence: 'A ___ light glowed in the woods.', emoji: '🌫️' },
    { word: 'sympathy', def: 'caring about another\'s feelings', sentence: 'She showed ___ when the puppy hurt its paw.', emoji: '💝' },
    { word: 'tradition', def: 'a long-followed custom', sentence: 'Eating turkey is a Thanksgiving ___.', emoji: '🦃' },
    { word: 'reluctant', def: 'unwilling; hesitant', sentence: 'He was ___ to try the spinach.', emoji: '😟' },
    { word: 'optimistic', def: 'expecting good things', sentence: 'She felt ___ about the test.', emoji: '🌞' },
    { word: 'pessimistic', def: 'expecting bad things', sentence: 'He was ___ about the rainy forecast.', emoji: '🌧️' },
    { word: 'consequence', def: 'a result of an action', sentence: 'Every choice has a ___.', emoji: '➡️' },
    { word: 'fortunate', def: 'lucky', sentence: 'We were ___ to find a parking spot.', emoji: '🍀' },
    { word: 'collaborate', def: 'to work together', sentence: 'Scientists ___ on big projects.', emoji: '🤝' }
  ]
}

// Synonym pairs for the synonym question template
export const SYNONYMS = [
  ['happy', 'glad'],
  ['big', 'large'],
  ['small', 'tiny'],
  ['quick', 'fast'],
  ['begin', 'start'],
  ['end', 'finish'],
  ['hard', 'difficult'],
  ['easy', 'simple'],
  ['smart', 'clever'],
  ['quiet', 'silent'],
  ['scared', 'afraid'],
  ['brave', 'courageous'],
  ['gigantic', 'huge'],
  ['ancient', 'old'],
  ['modern', 'new'],
  ['shout', 'yell']
]

// Antonym pairs — used by spelling MC for upper grades to provide
// meaning-distinguishing distractors alongside misspellings.
export const ANTONYMS = [
  ['hot', 'cold'],
  ['big', 'small'],
  ['large', 'small'],
  ['happy', 'sad'],
  ['happy', 'angry'],
  ['quick', 'slow'],
  ['fast', 'slow'],
  ['bright', 'dark'],
  ['hard', 'soft'],
  ['high', 'low'],
  ['up', 'down'],
  ['in', 'out'],
  ['begin', 'end'],
  ['ancient', 'modern'],
  ['gigantic', 'tiny'],
  ['enormous', 'tiny'],
  ['beautiful', 'ugly'],
  ['shout', 'whisper'],
  ['generous', 'selfish'],
  ['optimistic', 'pessimistic'],
  ['frequent', 'occasional'],
  ['brave', 'scared'],
  ['fragile', 'strong'],
  ['fortunate', 'unlucky'],
  ['reluctant', 'eager']
]
